[package]
name = "crypt-tool"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
getrandom = "0.2"
hex = "0.4"
sha2 = "0.10"
x25519-dalek = { version = "=2.0.1", default-features = false, features = [
  "static_secrets"
] }
aes-siv = "0.5"
